# XDG paths
#export XDG_CONFIG_HOME="$HOME/.config"      # XDG Default Config
export XDG_CONFIG_HOME="$HOME/System/config"
#export XDG_CACHE_HOME="$HOME/.cache"        # XDG Default Cache
export XDG_CACHE_HOME="$HOME/System/cache"
#export XDG_DATA_HOME="$HOME/.local/share"   # XDG Default Share
export XDG_DATA_HOME="$HOME/System/data"
#export XDG_STATE_HOME="$HOME/.local/state"  # XDG Default State
export XDG_STATE_HOME="$HOME/System/state"
#export SYSTEM_BIN_HOME="$HOME/.local/bin"   # XDG Default Bin
export SYSTEM_BIN_HOME="$HOME/System/bin"
export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"
export XSERVERAUTH="$XDG_RUNTIME_DIR/Xserverauth"

PATH="$SYSTEM_BIN_HOME:$PATH"

if [ -f "$XDG_CONFIG_HOME/bash/bashrc" ]; then
    source "$XDG_CONFIG_HOME/bash/bashrc"
fi