# XDG paths
export XDG_CONFIG_HOME="$HOME/.config"      # Soon "$HOME/System/config"
export XDG_CACHE_HOME="$HOME/.cache"        # Soon "$HOME/System/cache"
export XDG_DATA_HOME="$HOME/.local/share"   # Soon "$HOME/System/data"
export XDG_STATE_HOME="$HOME/.local/state"  # Soon "$HOME/System/state"
export SYSTEM_BIN_HOME="$HOME/.local/bin"   # Soon "$HOME/System/bin"
export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"
export XSERVERAUTH="$XDG_RUNTIME_DIR/Xserverauth"

PATH="$SYSTEM_BIN_HOME:$PATH"

if [ -f "$XDG_CONFIG_HOME/bash/bashrc" ]; then
    source "$XDG_CONFIG_HOME/bash/bashrc"
fi